name: Deploy
on:
  push:
    branches: [master]
jobs:
  prune-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: c-hive/gha-remove-artifacts@v1.2.0
      with:
        age: '0 minutes'
        skip-recent: 2 # KEEP PREVIOUS FOR ROLLBACK
  build:
    runs-on: ubuntu-latest
    needs: prune-artifacts
    steps:
    - uses: actions/checkout@master
      with:
        ref: refs/heads/master
    - run: make build tag=${{ github.event.repository.name }}
    - run: make save tag=${{ github.event.repository.name }} sha=${{ github.sha }}
    - uses: actions/upload-artifact@v2
      with:
        name: build@${{ github.sha }}
        path: ${{ github.sha }}.tar
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: refs/heads/master
    - uses: actions/download-artifact@v2
      with:
        name: build@${{ github.sha }}
    - env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< "${{ secrets.ansible_ssh_key }}"
        ssh-add -l
    - env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: make deploy tag=${{ github.event.repository.name }} sha=${{ github.sha }} slack_token=${{ secrets.slack_token }} slack_secret=${{ secrets.slack_secret }} openai_secret=${{ secrets.openai_secret }}
